---
# Creates a cloud VM3 on Chameleon Cloud
- name: "Create VM3"
  openstack.cloud.server:
      state: present
      name: team16_ansible_VM3
      image: 2067e3e4-057b-4fb9-a7f9-e8688cd5012b
      key_name: team16
      timeout: 200
      flavor: 2
      floating_ips:
        - 129.114.24.223
      security_groups: ["ENABLE_KAFKA_COUCHDB", "ENABLE_SSH"]
      wait: yes
      nics:
        - net-name: CH-819381-net
...