
---
# CS4287-5287
# Author: Group 16
# Created: Fall 2021
#
# This is a declarative approach to describe a Kubernetes based
# service and deployment of zookeeper

apiVersion: v1
kind: Service
metadata:
  name: couch-db-srv
spec:
  type: NodePort   # by using NodePort, the service is published to outside world.
  selector:
    app: couch-db     # used to match the pod(s) that run the actual couch DB server
  ports:
    - name: couch-db-port    # not needed, but I have added this
      protocol: TCP     # this is default (so not needed either)
      port: 5984   # the port used by the server inside the pod/container
      targetPort: 5984   # not sure if we need this because if not specified, it is same as port
      nodePort: 30003  # this is what will be externally published
...
